do $$
declare did uuid; vid uuid; cat uuid;
begin
  insert into document_categories(code,name,sort_order) select 'FORMS','Forms',900 where not exists(select 1 from document_categories where name='Forms');
  insert into document_categories(code,name,sort_order) select 'RES','Resources',901 where not exists(select 1 from document_categories where name='Resources');
  select id into cat from document_categories where name='Forms';

  if not exists(select 1 from documents where code='F-REIMB') then
    insert into documents(code,title,category_id,doc_type,requires_signature,library,recipients,conditions,active)
      values('F-REIMB','Employee Reimbursement Form',cat,'web_form',false,'form', $j$[{"label": "Accounts", "email": "accounts@nuway.com.au"}]$j$::jsonb, null, true) returning id into did;
    insert into document_versions(document_id,version_no,form_schema) values(did,1, $s${"type": "guided", "pages": [{"title": "Employee Reimbursement", "blocks": [{"type": "field", "input": "date", "name": "date", "label": "Date", "required": true}, {"type": "field", "input": "text", "name": "store", "label": "Store", "required": true}, {"type": "field", "input": "text", "name": "name", "label": "Your name", "required": true}, {"type": "field", "input": "text", "name": "home_store", "label": "Home store (if borrowed staff)"}, {"type": "field", "input": "number", "name": "amount", "label": "Refund amount ($)", "required": true}, {"type": "field", "input": "textarea", "name": "reason", "label": "Reason for expense", "required": true}, {"type": "note", "text": "Attach your receipts and any paperwork when you email this. Funds transfer to your wages account unless bank details are provided below."}, {"type": "field", "input": "text", "name": "bsb", "label": "BSB (only if NOT your wages account)"}, {"type": "field", "input": "text", "name": "account", "label": "Account number (only if NOT your wages account)"}, {"type": "ack", "name": "ack", "text": "I confirm the details provided are correct. Nuway is not responsible for incorrect details."}]}]}$s$::jsonb) returning id into vid;
    update documents set current_version_id=vid where id=did;
  end if;

  if not exists(select 1 from documents where code='F-GRIEV') then
    insert into documents(code,title,category_id,doc_type,requires_signature,library,recipients,conditions,active)
      values('F-GRIEV','Employee Complaint / Grievance Form',cat,'web_form',false,'form', $j$[{"label": "My Store Manager / Supervisor", "email": "CHANGE-ME@nuway.com.au"}, {"label": "Area Manager", "email": "CHANGE-ME@nuway.com.au"}, {"label": "Corporation Administration", "email": "accounts@nuway.com.au"}]$j$::jsonb, null, true) returning id into did;
    insert into document_versions(document_id,version_no,form_schema) values(did,1, $s${"type": "guided", "pages": [{"title": "Employee Complaint / Grievance", "blocks": [{"type": "clause", "text": "Complete this form and send it to your manager or supervisor. If your manager or supervisor is the subject of the grievance, send it to your area manager or Nuway Corporation Administration instead. This information is treated confidentially, however if your complaint is about another person, the person handling it will generally need to share details with that person to obtain their response."}, {"type": "field", "input": "text", "name": "name", "label": "Staff member (your full name)", "required": true}, {"type": "field", "input": "text", "name": "position", "label": "Your position", "required": true}, {"type": "field", "input": "date", "name": "date_submitted", "label": "Date form submitted", "required": true}, {"type": "field", "input": "date", "name": "date_arose", "label": "Date the problem or concern arose"}, {"type": "field", "input": "select", "name": "about_person", "options": ["No", "Yes"], "label": "Is your complaint about another person?", "required": true}, {"type": "field", "input": "textarea", "name": "person_details", "label": "If yes, identify the person, their main store and position"}, {"type": "field", "input": "textarea", "name": "details", "label": "Provide specific details of your complaint", "required": true}, {"type": "field", "input": "select", "name": "before", "options": ["No", "Yes"], "label": "Has this happened before?"}, {"type": "field", "input": "textarea", "name": "before_details", "label": "If yes, please provide details"}, {"type": "field", "input": "textarea", "name": "impact", "label": "What impact has this had on you?"}, {"type": "field", "input": "textarea", "name": "outcome", "label": "What outcome or remedy are you seeking to resolve your complaint?"}, {"type": "field", "input": "select", "name": "action_taken", "options": ["No", "Yes"], "label": "Have you taken any action to resolve your complaint?"}, {"type": "field", "input": "textarea", "name": "action_details", "label": "If yes, please provide details"}, {"type": "field", "input": "select", "name": "method", "options": ["Informal complaint procedure", "Formal complaint procedure"], "label": "Preferred method for dealing with the complaint", "required": true}, {"type": "ack", "name": "ack", "text": "The information I have provided in this form is true and correct."}]}]}$s$::jsonb) returning id into vid;
    update documents set current_version_id=vid where id=did;
  end if;
end $$;